matrix:
    include:
        - language: go
            sudo: required
            services:
                - docker
            script:
                - export GO111MODULE=on
                - make build_base_image
                - make format
                - make test
